FROM node:16.1
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN mkdir /work
# COPY ./face_front /work
WORKDIR /work

# RUN npm init -y
# CMD npm install -g npm@7.13.0
# RUN npm install
# RUN npm config set registry https://registry.npm.taobao.org/
# CMD sleep infinity
CMD npm install && npm run dev