FROM python:3.6
# 设置时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN mkdir /work
WORKDIR /work
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install kafka-python
RUN pip install pymongo
CMD ["/bin/bash", "run.sh"]